FROM python:3.12-slim

WORKDIR /var/www/html/api

RUN pip install langchain langchain-google-genai langchain-core python-dotenv fastapi uvicorn python-multipart PyPDF2 watchdog langchain-huggingface

COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
